#!/usr/bin/env bash
leftwm command "UnloadTheme"

# = Remove Proccess {{{ 
pkill polybar
pkill dunst
pkill feh
pkill compton
pkill picom
# }}} 

# = Remove Config Paths {{{  
rm "$HOME/.config/dunst" 
rm "$HOME/.config/rofi"
# }}} 
