#!/usr/bin/env bash
leftwm command "UnloadTheme"

# = Remove Proccess {{{ 
pkill dunst
pkill feh
pkill compton
pkill picom
pkill eww
# }}} 

# = Remove Config Paths {{{  
rm -rf "$HOME/.config/eww"
rm -rf "$HOME/.config/dunst" 
rm -rf "$HOME/.config/rofi"
# }}} 
