#!/usr/bin/env bash
export $(dbus-launch)
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# = Down Old Theme {{{ 
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down
# }}} 
# = Config Rofi {{{ 
if [ -x "$(command -v rofi)" ]; then 
	mkdir -p "/home/$USER/.config/rofi"
	cp -r "${SCRIPTPATH}/rofi/" "/home/$USER/.config/"
fi
# }}} 
# = Config Dunst {{{ 
if [ -x "$(command -v dunst)" ]; then
    mkdir -p "/home/$USER/.config/dunst"
    echo "$SCRITPATH"
    cp "${SCRIPTPATH}/dunstrc" "/home/$USER/.config/dunst/"
    dunst &> /dev/null &
fi
# }}}

# = Config picom {{{ 
if [ -x "$(command -v picom)" ]; then
    picom --config "${SCRIPTPATH}/picom.conf" &> /dev/null &
fi
# }}} 

# = Config feh {{{ 
if [ -x "$(command -v feh)" ]; then
    feh --bg-fill "$SCRIPTPATH/wallpaper.jpg" &> /dev/null &
fi
# }}} 

# = Up Theme {{{ 
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"
if [ -x "$(command -v polybar)" ]; then
    pkill polybar
    monitors="$(polybar -m | sed s/:.*// | tac)"
    while read -r display; do
        MONITOR=$display polybar -c "$SCRIPTPATH/polybar.ini" mainbar &> /dev/null &
    done <<< "$monitors"
    exit 0
fi
# }}} 
