#!/usr/bin/env bash
export $(dbus-launch)
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Clean up previous theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Config Rofi
if [ -x "$(command -v rofi)" ]; then
	mkdir -p "/home/$USER/.config/rofi"
	cp -r "${SCRIPTPATH}/rofi/" "/home/$USER/.config/"
fi

# Config Dunst
if [ -x "$(command -v dunst)" ]; then
    mkdir -p "/home/$USER/.config/dunst"
    cp "${SCRIPTPATH}/dunstrc" "/home/$USER/.config/dunst/"
    dunst &> /dev/null &
fi

# Config picom
if [ -x "$(command -v picom)" ]; then
    picom --config "${SCRIPTPATH}/picom.conf" &> /dev/null &
fi

# Config wallpaper
if [ -x "$(command -v feh)" ]; then
    feh --bg-fill "$SCRIPTPATH/wallpaper.jpg" &> /dev/null &
fi

# Load LeftWM theme
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Launch EWW
if [ -x "$(command -v eww)" ]; then
    # Kill any existing EWW instance
    pkill eww
    
    # Create EWW config directory 
    mkdir -p "/home/$USER/.config/eww"
    
    # Copy Config File to EWW directory 
    cp -r "$SCRIPTPATH/eww" "/home/$USER/.config"
    
    # Start EWW
    eww daemon &> /dev/null &
    sleep 0.5  # Give the daemon time to start
    eww open bar &> /dev/null &
fi
